### ISSUE TITLE
Road to 1.0

### ISSUE THREAD

**Issue by pjohansson** [pjohansson/inkling#5]
I'd like to set some goals for this project. Maybe I'll even get around to completing them. Either way, this is my attempt to formalize my requirements for bringing this project to a "usable" state, i.e. 1.0.

- [ ] Finalize user API, notably how the `Story` returns information and when it returns to wait for user action (#2)
- [ ] Properly document which features from Ink which can and cannot be used, with examples
- [ ] Implement [variable assignment](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#2-logic) using `~` in the story text
- [ ] Add [shuffle sequences](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#sequences-cycles-and-other-alternatives) with `rand`
- [ ] Add [include statements](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#script-files-can-be-combined) for other files
- [ ] Add [conditional and multiline blocks](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#3-conditional-blocks-ifelse)
- [x] Relicense project, since CC-BY-ShareAlike is too restrictive for third-party use (#3)

**Comment by alexispurslane** [comment]
I'm seriously considering using this if you hit 1.0 before I recover from my concussion and am able to work on programming projects again. The biggest must-have feature for me is probably being able to call Rust functions from ink, to make in-game events react to your dialogue choices. Overall, this looks really good, keep up the good work!
